/home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py
  /home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py:10:8 - error: Import "polars" could not be resolved (reportMissingImports)
  /home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py:11:8 - error: Import "plotly.graph_objects" could not be resolved (reportMissingImports)
  /home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py:13:8 - error: Import "plotly.express" could not be resolved (reportMissingImports)
  /home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py:293:18 - error: "add_trace" is not a known attribute of "None" (reportOptionalMemberAccess)
  /home/alex/code/machineconfig/src/machineconfig/scripts/python/count_lines.py:295:18 - error: "update_layout" is not a known attribute of "None" (reportOptionalMemberAccess)
/home/alex/code/machineconfig/src/machineconfig/scripts/python/interactive.py
  /home/alex/code/machineconfig/src/machineconfig/scripts/python/interactive.py:190:16 - error: "main" is not a known attribute of module "machineconfig.scripts.python.repos" (reportAttributeAccessIssue)
6 errors, 0 warnings, 0 informations
